In [16]:
import pandas as pd
from datetime import date, timedelta
from thetadata import ThetaClient, OptionReqType, OptionRight, DateRange, StockReqType
from ratelimiter import RateLimiter
import pandas as pd

In [22]:

df_spy = pd.read_csv("SPY.csv")
df_qqq = pd.read_csv("QQQ.csv")

,Date,Open,High,Low,Close,Adj Close,Volume
0,2020-10-08,282.399994,282.470001,280.309998,281.410004,277.508881,25443300
1,2020-10-09,283.109985,285.790009,282.709991,285.709991,281.749329,30201100
2,2020-10-12,290.549988,297.459991,289.470001,294.529999,290.447021,79370700
3,2020-10-13,296.390015,297.049988,293.109985,294.519989,290.437195,64240000
4,2020-10-14,295.350006,296.350006,290.260010,292.059998,288.011322,36949100
...,...,...,...,...,...,...,...
561,2022-12-30,263.619995,266.410004,262.290009,266.279999,266.279999,37796100
562,2023-01-03,268.649994,270.149994,262.130005,264.480011,264.480011,42335300
563,2023-01-04,266.640015,267.450012,262.529999,265.739990,265.739990,47754900
564,2023-01-05,264.040009,264.209991,261.260010,261.579987,261.579987,45396700
565,2023-01-06,263.350006,269.940002,260.339996,268.799988,268.799988,54573600

In [24]:
# Get options data:

def all_fridays(year):
    d = date(year, 1, 1)
    # First Friday
    d += timedelta(days = ((4 + 7) - d.weekday()) % 7)
    while d.year == year:
        yield d
        
def next_fridays(cur_date):
    return cur_date + timedelta(days = ((4 + 7) - d.weekday()) % 7)


class Portfolio:
    def __init__(self, cash=100_000, name='default_name'):
        self.cash = cash
        self.stocks = {}
        self.name = name
    
    def buy(symbol, price, quantity):
        if self.cash < price * quantity:
            raise Exception('Porfolio {} has insufficient cash to buy stock. Cash needed: {}, actual cash: {}'.format(
                self.name, price * quantity, self.cash
            ))
        
        self.cash -= price * quantity
        if symbol not in self.stocks:
            self.stocks[symbol] = quantity
        else:
            self.stock[symbol] += quantity
        
    def sell(symbol, price, quantity):
        if symbol not in self.stocks:
            raise Exception('Symbol {} can\'t be found in portfolio {}'.format(symbol, self.name))
        if self.stocks[symbol] < quantity:
            raise Exception('Symbol {} in portfolio {} is insufficient. Expected to sell {}, actual quantity {}'.format(symbol, self.name, quantity, self.stocks[symbol]))
        self.cash += price * quantity
        self.stocks[symbol] -= quantity
    
    def current_value(symbol_to_price):
        res = self.cash
        for key, val in res.items():
            if key not in symbol_to_price:
                raise Exception('Did not find symbol: {}.'.format(key))
            
            res += val * symbol_to_price[key]
        return res
    
    
    

portfolio = Portfolio()


client = ThetaClient()
with client.connect():
    
    out = client.get_strikes("SPY", date('2020-10-08'))

If you require API support, feel free to join our discord server! https://discord.thetadata.us
------------------------------------------------------------------------------------------------
You are using the free version of Theta Data. You are currently limited to 20 requests / minute.
A data subscription can be purchased at https://thetadata.net. If you already have a ThetaData
subscription, specify the username and passwd parameters.
------------------------------------------------------------------------------------------------
Starting Theta Terminal [v0.7.9 REV: A]  -->  Config: /Users/pengfeisong/ThetaData/ThetaTerminal
[MDDServer] Attempting login as default  -->  CONNECTED: [nj-a.thetadata.us:12001], Bundle: FREE, Permissions: End of Day(EOD)